/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthReimbEditTicketLazyImport = createFileRoute(
  '/_auth/reimb/editTicket',
)()
const AuthReimbAddTicketLazyImport = createFileRoute('/_auth/reimb/addTicket')()
const AuthAuthRegisterLazyImport = createFileRoute('/_auth/auth/register')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthReimbEditTicketLazyRoute = AuthReimbEditTicketLazyImport.update({
  id: '/_auth/reimb/editTicket',
  path: '/reimb/editTicket',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/reimb/editTicket.lazy').then((d) => d.Route),
)

const AuthReimbAddTicketLazyRoute = AuthReimbAddTicketLazyImport.update({
  id: '/_auth/reimb/addTicket',
  path: '/reimb/addTicket',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/reimb/addTicket.lazy').then((d) => d.Route),
)

const AuthAuthRegisterLazyRoute = AuthAuthRegisterLazyImport.update({
  id: '/_auth/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/auth/register.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reimb/addTicket': {
      id: '/_auth/reimb/addTicket'
      path: '/reimb/addTicket'
      fullPath: '/reimb/addTicket'
      preLoaderRoute: typeof AuthReimbAddTicketLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reimb/editTicket': {
      id: '/_auth/reimb/editTicket'
      path: '/reimb/editTicket'
      fullPath: '/reimb/editTicket'
      preLoaderRoute: typeof AuthReimbEditTicketLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auth/register': typeof AuthAuthRegisterLazyRoute
  '/reimb/addTicket': typeof AuthReimbAddTicketLazyRoute
  '/reimb/editTicket': typeof AuthReimbEditTicketLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth/register': typeof AuthAuthRegisterLazyRoute
  '/reimb/addTicket': typeof AuthReimbAddTicketLazyRoute
  '/reimb/editTicket': typeof AuthReimbEditTicketLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_auth/auth/register': typeof AuthAuthRegisterLazyRoute
  '/_auth/reimb/addTicket': typeof AuthReimbAddTicketLazyRoute
  '/_auth/reimb/editTicket': typeof AuthReimbEditTicketLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/register' | '/reimb/addTicket' | '/reimb/editTicket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/register' | '/reimb/addTicket' | '/reimb/editTicket'
  id:
    | '__root__'
    | '/'
    | '/_auth/auth/register'
    | '/_auth/reimb/addTicket'
    | '/_auth/reimb/editTicket'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthAuthRegisterLazyRoute: typeof AuthAuthRegisterLazyRoute
  AuthReimbAddTicketLazyRoute: typeof AuthReimbAddTicketLazyRoute
  AuthReimbEditTicketLazyRoute: typeof AuthReimbEditTicketLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthAuthRegisterLazyRoute: AuthAuthRegisterLazyRoute,
  AuthReimbAddTicketLazyRoute: AuthReimbAddTicketLazyRoute,
  AuthReimbEditTicketLazyRoute: AuthReimbEditTicketLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth/auth/register",
        "/_auth/reimb/addTicket",
        "/_auth/reimb/editTicket"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_auth/auth/register": {
      "filePath": "_auth/auth/register.lazy.tsx"
    },
    "/_auth/reimb/addTicket": {
      "filePath": "_auth/reimb/addTicket.lazy.tsx"
    },
    "/_auth/reimb/editTicket": {
      "filePath": "_auth/reimb/editTicket.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
