package com.example.ERS.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.OffsetDateTime;


@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Table(name="reimbursement")
public class Reimbursement {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @EqualsAndHashCode.Include
    private Integer reimbursementId;
    /**
     * A description for this Reimbursement (must be unique and not blank)
     */
    private String description;
    /*
     * The amount for reimbursement 
     */
    private Double amount;
    /**
     * A status for this Reimbursement 
     */
    private String status; // should be pending by default
    /*
     * The id of the requesting user
     */
    @ManyToOne
    @JoinColumn(name="userid")
    @JsonBackReference
    private User userID;

    private OffsetDateTime submitted;

    private String project;

    /**
     * When posting a new Reimbursement, the id can be generated by the database. In that case, a constructor without
     * ReimbursementId is needed.
     * @param description
     * @param amount
     * @param project
     */
    public Reimbursement(String description, Double amount, String project) {
        this.description = description;
        this.amount = amount;
        this.project = project;
    }

}
